services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 39012:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - app
      - server

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bloglist-frontend
    environment:
      - VITE_BACKEND_URL=/api

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=${MONGODB_URI}
        - SECRET=${SECRET}
        - PORT=3003
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
      - PORT=3003
      - NODE_ENV=production
    container_name: bloglist-backend
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-prod
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
      - PORT=${PORT}
      - NODE_ENV=production
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

volumes:
  mongo_data:
    name: mongo-prod-data

