# fly.toml app configuration file generated for fullstackopen-phonebook-juhamikael on 2023-07-31T01:47:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackopen-phonebook-juhamikael"
primary_region = "arn"

[env]
  port = "8080"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
